### ISSUE TITLE
BitwardenDecryptBrute Is Mislicensed

### ISSUE THREAD

**Issue by GurpreetKang** [S3cur3Th1sSh1t/BitwardenDecryptBrute#1]
I'm glad that you found [BitwardenDecrypt](https://github.com/GurpreetKang/BitwardenDecrypt) useful.   :smiley:

Since my original software is [licensed under GPL-3.0](https://github.com/GurpreetKang/BitwardenDecrypt/blob/master/LICENSE) this derivative work must also be licensed under GPL-3.0 or a compatible license, which the BSD-3-Clause license is not. :no_entry_sign:

**Comment by S3cur3Th1sSh1t** [comment]
Fixed ;-)
